apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app.kubernetes.io/name: homelab-autoscaler
    app.kubernetes.io/managed-by: kustomize
  name: manager-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: manager-role
subjects:
- kind: ServiceAccount
  name: controller-manager
  namespace: ${HOMELAB_AUTOSCALER_NAMESPACE:-homelab-autoscaler-system}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app.kubernetes.io/name: homelab-autoscaler
    app.kubernetes.io/managed-by: kustomize
  name: homelab-autoscaler-controller-manager-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: manager-role
subjects:
- kind: ServiceAccount
  name: homelab-autoscaler-controller-manager
  namespace: ${HOMELAB_AUTOSCALER_NAMESPACE:-homelab-autoscaler-system}
