apiVersion: infra.homecluster.dev/v1alpha1
kind: Group
metadata:
  labels:
    app.kubernetes.io/name: homelab-autoscaler
    app.kubernetes.io/managed-by: kustomize
  name: group-sample
spec:
  maxSize: 3
  scaleDownUtilizationThreshold: 0.3
  scaleDownUnneededTime: "5m"
  scaleDownUnreadyTime: "2m"
  maxNodeProvisionTime: "10m"
