apiVersion: infra.homecluster.dev/v1alpha1
kind: Node
metadata:
  labels:
    app.kubernetes.io/name: homelab-autoscaler
    app.kubernetes.io/managed-by: kustomize
  name: node-sample
spec:
  kubernetesNodeName: "example-node"
  powerState: "on"
  pricing:
    hourlyRate: "1.0"
    podRate: "0.1"
  startupPodSpec:
    image: busybox:latest
    command: ["echo", "Node startup simulation"]
  shutdownPodSpec:
    image: busybox:latest
    command: ["echo", "Node shutdown simulation"]
